version: '3'

services:
  mock-server:
    container_name: mock-server
    image: mockserver/mockserver
    ports:
      - 1080:1080
    networks:
      - calculator-net
  db:
    container_name: some-postgres
    image: postgres:12-alpine
    ports:
      - 5432:5432
    networks:
      - calculator-net
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=calculator
  tomcat:
    container_name: ms-calculator
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - calculator-net
networks:
  calculator-net: